baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "sparklyr: R interface for Apache Spark"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    weight = 1
    name = "Reference"
    url = "/reference/"

[[menu.main]]
    weight = 2
    name = "News"
    url = "/news/"
    
    
[[menu.main]]
    weight = 2
    name = "Documents"
    url = "/documents/"    
    


[params]

    
    description = "A website built through Hugo and blogdown (and gitdown)."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"


[params.logo]
    url = "sparklyr.png"
    width = 1
    height = 1
    alt = "sparklyr"

[social]
	twitter = "rstudio"
	github  = "rstudio/sparklyr"
	email   = "info@rstudio.com"
	
[params.palette]
  	primary = "rstudio-dark"
  	accent  = "orange"

